### ISSUE TITLE
Check out generator-reveal

### ISSUE THREAD

**Issue by janraasch** [nicdaCosta/generator-revealjs#1]
Hi,

you may wanna check out [generator-reveal](https://github.com/slara/generator-reveal). Seems like we are trying to solve some of the same problems.

**Comment by nicdaCosta** [comment]
Thanks :) 

I actually cam across this the other day while doing a search on NPM. Will take a closer look and see if i can help in any way.

Also, will update my readme to link to this for a more verbose generator, as mine is more of a simple generator that was created purely for my own use so i can easily include my custom styles when needing to creating slides.

Please correct me if i am wrong, but the slides seem to be created from a simple array with various attributes that are then compiled to the relevant html for the slides? Any particular reason for going that route as opposed to directly generating and editing the html per slide?

**Comment by janraasch** [comment]
Sorry for the late reply.

> Please correct me if i am wrong, but the slides seem to be created from a simple array with various attributes that are then compiled to the relevant html for the slides?

Yes. The idea behind the format

``` json
{
    "filename": "slide-title.md",
    "attr": {
        "data-background": "#ff0000"
    }
}
```

of objects inside the `slides/list.json` `Array` was that, if you want to write your slides with **markdown**, you cannot (and probably do not want to) directly set attributes on the respective `<section>` element of your slide inside your `.md` file. Also, this makes it possible, to have a slide which only consists of an background-image and no html/markdown content at all, e.g.

``` json
{
    "attr": {
        "data-background": "http://example.com/image.png"
    }
}
```

I am not sure what you mean by

> Any particular reason for going that route as opposed to directly generating and editing the html per slide?

You can generate a slide with `yo reveal:slide "My HTML slide"`. This will generate a `slides/my-html-slide.html` file which one can edit.

Explaining this, I realize we need to work on our `README.md` :)

**Comment by janraasch** [comment]
I'll close this, since there was no action in quite a while :-).
